import { ReportLanguage } from './types';

export const REPORT_STRINGS = {
  EN: {
    cover: {
      title: "Predictive Multi-Factor VRU Risk Assessment",
      subtitle: "Safety Audit & Compliance Report",
      systemName: "SENTINEL AI",
      mode: "Mode",
      environment: "Environment",
      sessionID: "Session ID",
      date: "Date & Time",
      generatedBy: "Generated by",
      location: "Location",
      coordinates: "Coordinates",
      confidential: "CONFIDENTIAL SAFETY AUDIT",
    },
    executive: {
      title: "Executive Summary",
      safetyIndex: "Safety Index",
      riskLevel: "Risk Classification",
      confidence: "AI Confidence",
      alerts: "Critical Alerts",
      analysis: "Automated Analysis",
      fallbackPrefix: "Automated Analysis: ",
    },
    timeline: {
      title: "Risk Timeline Analysis",
      yAxis: "Risk Score",
      xAxis: "Session Duration",
    },
    breakdown: {
      title: "Multi-Parameter Risk Breakdown",
      headers: ["Risk Factor", "Measured Value", "Weight", "Contribution", "Status"],
      dominant: "Dominant Factor",
    },
    xai: {
      title: "Explainable AI (XAI) Model",
      formula: "Risk Calculation Model",
      explanation: "Model Interpretation",
    },
    context: {
      title: "Environmental & Sensor Context",
      topology: "Topological Analysis",
      density: "Density Analysis",
      sensor: "Sensor Integrity",
    },
    recommendations: {
      title: "Strategic Safety Recommendations",
    },
    footer: {
      text: "SENTINEL AI | Automated Safety Audit System",
      page: "Page",
    },
    factors: {
      distance: "Proximity",
      relativeSpeed: "Relative Speed",
      density: "Crowd Density",
      topology: "Topology",
      infrastructure: "Infrastructure",
      sensor: "Sensor Uncertainty",
    }
  },
  FR: {
    cover: {
      title: "Évaluation Prédictive des Risques VRU",
      subtitle: "Rapport d'Audit de Sécurité",
      systemName: "SENTINEL AI",
      mode: "Mode",
      environment: "Environnement",
      sessionID: "ID de Session",
      date: "Date et Heure",
      generatedBy: "Généré par",
      location: "Lieu",
      coordinates: "Coordonnées",
      confidential: "AUDIT DE SÉCURITÉ CONFIDENTIEL",
    },
    executive: {
      title: "Résumé Exécutif",
      safetyIndex: "Indice de Sécurité",
      riskLevel: "Classification du Risque",
      confidence: "Confiance IA",
      alerts: "Alertes Critiques",
      analysis: "Analyse Automatisée",
      fallbackPrefix: "Analyse Automatisée : ",
    },
    timeline: {
      title: "Analyse Chronologique des Risques",
      yAxis: "Score de Risque",
      xAxis: "Durée de la Session",
    },
    breakdown: {
      title: "Décomposition Multi-Paramètres",
      headers: ["Facteur de Risque", "Valeur Mesurée", "Poids", "Contribution", "Statut"],
      dominant: "Facteur Dominant",
    },
    xai: {
      title: "Modèle d'IA Explicable (XAI)",
      formula: "Modèle de Calcul de Risque",
      explanation: "Interprétation du Modèle",
    },
    context: {
      title: "Contexte Environnemental et Capteurs",
      topology: "Analyse Topologique",
      density: "Analyse de Densité",
      sensor: "Intégrité des Capteurs",
    },
    recommendations: {
      title: "Recommandations Stratégiques",
    },
    footer: {
      text: "SENTINEL AI | Système d'Audit de Sécurité Automatisé",
      page: "Page",
    },
    factors: {
      distance: "Proximité",
      relativeSpeed: "Vitesse Relative",
      density: "Densité de Foule",
      topology: "Topologie",
      infrastructure: "Infrastructure",
      sensor: "Incertitude Capteur",
    }
  }
};

export class LocalizationManager {
  static getStrings(lang: ReportLanguage) {
    return REPORT_STRINGS[lang];
  }
}
