
export type ReportLanguage = 'EN' | 'FR';

export const REPORT_STRINGS = {
  EN: {
    cover: {
      title: "Predictive Multi-Factor VRU Risk Assessment Report",
      systemName: "VRU-Guard AI",
      mode: "Mode",
      environment: "Environment",
      sessionID: "Session ID",
      date: "Date & Time",
      generatedBy: "Generated by",
      location: "Location",
      coordinates: "Coordinates",
    },
    executiveSummary: {
      title: "EXECUTIVE SUMMARY",
      avgRisk: "Average Risk Score",
      maxRisk: "Maximum Risk",
      totalAlerts: "Total Alerts",
      dominantFactor: "Dominant Risk Factor",
      gpsIntegrity: "GPS Integrity Score",
      riskConfidence: "Risk Confidence",
    },
    vruProfile: {
      title: "VRU PROFILE & CONTEXT",
      type: "VRU Type",
      infrastructure: "Infrastructure Used",
      compatibility: "Compatibility Score",
      avgSpeed: "Average Speed",
      behavior: "Behavioral Pattern",
    },
    riskBreakdown: {
      title: "MULTI-PARAMETER RISK BREAKDOWN",
      headers: ["Factor", "Normalized Value", "Weight", "Contribution %", "Impact Level"],
      factors: {
        distance: "Distance",
        relativeSpeed: "Relative Speed",
        density: "Density",
        topology: "Topology",
        infrastructure: "Infrastructure",
        sensor: "Sensor Uncertainty",
      },
    },
    topological: {
      title: "TOPOLOGICAL ANALYSIS",
      intersection: "Intersection Proximity",
      curvature: "Road Curvature",
      complexZone: "Complex Zone Detection",
      mismatch: "Infrastructure Mismatch",
    },
    density: {
      title: "DENSITY & SPATIAL ANALYSIS",
      localDensity: "Local Density",
      highRiskZone: "High-Risk Zone Detection",
    },
    sensor: {
      title: "SENSOR INTEGRITY & CONFIDENCE",
      rmse: "Average RMSE",
      stability: "Signal Stability Index",
      confidence: "Risk Confidence",
      adjustment: "Uncertainty Adjustment",
    },
    timeline: {
      title: "RISK TIMELINE GRAPH",
    },
    xai: {
      title: "EXPLAINABLE AI SECTION",
      formula: "Mathematical Formula",
      contributions: "Factor Contributions",
    },
    recommendations: {
      title: "SAFETY RECOMMENDATIONS",
    },
    footer: {
      text: "VRU-Guard AI | Confidential Safety Report",
      page: "Page",
    },
  },
  FR: {
    cover: {
      title: "Rapport d'Évaluation Prédictive Multi-Facteurs des Risques VRU",
      systemName: "VRU-Guard AI",
      mode: "Mode",
      environment: "Environnement",
      sessionID: "ID de Session",
      date: "Date et Heure",
      generatedBy: "Généré par",
      location: "Lieu",
      coordinates: "Coordonnées",
    },
    executiveSummary: {
      title: "RÉSUMÉ EXÉCUTIF",
      avgRisk: "Score de Risque Moyen",
      maxRisk: "Risque Maximum",
      totalAlerts: "Total des Alertes",
      dominantFactor: "Facteur de Risque Dominant",
      gpsIntegrity: "Score d'Intégrité GPS",
      riskConfidence: "Confiance du Risque",
    },
    vruProfile: {
      title: "PROFIL VRU & CONTEXTE",
      type: "Type de VRU",
      infrastructure: "Infrastructure Utilisée",
      compatibility: "Score de Compatibilité",
      avgSpeed: "Vitesse Moyenne",
      behavior: "Modèle Comportemental",
    },
    riskBreakdown: {
      title: "DÉCOMPOSITION DES RISQUES MULTI-PARAMÈTRES",
      headers: ["Facteur", "Valeur Normalisée", "Poids", "Contribution %", "Niveau d'Impact"],
      factors: {
        distance: "Distance",
        relativeSpeed: "Vitesse Relative",
        density: "Densité",
        topology: "Topologie",
        infrastructure: "Infrastructure",
        sensor: "Incertitude Capteur",
      },
    },
    topological: {
      title: "ANALYSE TOPOLOGIQUE",
      intersection: "Proximité Intersection",
      curvature: "Courbure de la Route",
      complexZone: "Détection Zone Complexe",
      mismatch: "Inadéquation Infrastructure",
    },
    density: {
      title: "ANALYSE SPATIALE & DENSITÉ",
      localDensity: "Densité Locale",
      highRiskZone: "Détection Zone à Haut Risque",
    },
    sensor: {
      title: "INTÉGRITÉ CAPTEUR & CONFIANCE",
      rmse: "RMSE Moyen",
      stability: "Indice de Stabilité du Signal",
      confidence: "Confiance du Risque",
      adjustment: "Ajustement d'Incertitude",
    },
    timeline: {
      title: "GRAPHIQUE CHRONOLOGIQUE DES RISQUES",
    },
    xai: {
      title: "SECTION IA EXPLICABLE (XAI)",
      formula: "Formule Mathématique",
      contributions: "Contributions des Facteurs",
    },
    recommendations: {
      title: "RECOMMANDATIONS DE SÉCURITÉ",
    },
    footer: {
      text: "VRU-Guard AI | Rapport de Sécurité Confidentiel",
      page: "Page",
    },
  },
};
